### PR TITLE
Add Art Blocks to known NFT markets

### PR DESCRIPTION
**Pull request by jamiew**
My favoritest Ethereum NFT platform: https://artblocks.io/

I think I got this right but lmk if I missed something

### CODE REVIEW

**Comment by kylemcdonald** [comment]
Hey Jamie! Definitely on the right track. Could you help me out with this a little bit? This is one of two contracts I have for Art Blocks. Here is the other one: https://etherscan.io/address/0x059edd72cd353df5106d2b9cc5ab83a52287ac3a

Could you check that these are both used by the same "Art Blocks" site? And if they are, please add both to `contracts.json`. If they are both NFTs, please add both to `marketplaces-collectibles-games.json`

Right now `contracts.json` is a more holistic approach that includes cash out wallets, exchanges, NFTs, ERC-20 tokens, and more that are required for running cryptoart marketplaces. If you know any other addresses associated with Art Blocks, please add them here.

`marketplaces-collectibles-games.json` only includes contracts that implement ERC-721 or equivalent (e.g. ERC-1155).

**Comment by jamiew** [comment]
Copy that, will fix

**Comment by jamiew** [comment]
@kylemcdonald added the second contract plus what appears to be their main hot wallet. starting to sneak some other fixes in too 

* `print_contracts` was failing since I was missing cached data and it wasn't loading my Etherscan API key
* add some of your instructions here to the README

happy to split these out into multiple PRs if you'd prefer

happy monday!

**Comment by jamiew** [comment]
btw – one could figure out which `data/contracts.json` are ERC-721-compatible just by querying the contract interface using a web3 provider API like Infura or Alchemy (or possibly even Etherscan?). 

I've done this in the past by checking for `balanceOf/ownerOf` functions, and `tokenURI` though that is technically optional. Collating by hand maybe more accurate but more work?

**Comment by kylemcdonald** [comment]
Thanks, great work. I wasn't loading the key originally for print_contracts because I didn't want it to check for updates—since that can take a while. But this is more correct.

**Comment by kylemcdonald** [comment]
Also, you could get all ERC-721 compatible contracts, yes. But there are a lot, and there are many that are unrelated to anything even vaguely resembling collectibles, cryptoart, or even game assets. And I feel confident that this currently represents a large (90%+) portion of what most people are talking about when they talk about these categories.

Your new contracts should be included in the next update (~24 hours).

**Comment by jamiew** [comment]
Yeah that’s a great point. I have a bunch of random “NFTs” that show up in
my wallet because they are 721 compatible but are definitely not art


-- 
@jamiew <https://twitter.com/jamiew> | https://jamiedubs.com
<https://www.jamiedubs.com/>

**Pull request merged**
